### PR TITLE
Pdm 2188

### PR DESCRIPTION
**Pull request by dineshshenoy**

### CODE REVIEW

**Comment by ekinesocotra** [comment]
Can you add more comments to the get_gg_details function to explain the resources accessed?

**Comment by ekinesocotra** [comment]
suds is not a standard module. should we add to requirements.txt?

**Comment by ekinesocotra** [comment]
can you give an example NVIC to run the file? Do i need a gg username/password?

**Comment by dineshshenoy** [comment]
Added clarifying comments based on feedback.  There is an example NVIC on line 76.   In order to use the script, a client would need a paid or evaluation license to Glasses Guide

**Pull request merged**
